#pragma once

#define OPEN_BRACKET_IDX 0

#define DAY_0_IDX 1
#define DAY_1_IDX 2

#define SLASH_0_IDX 3

#define MONTH_0_IDX 4
#define MONTH_1_IDX 5
#define MONTH_2_IDX 6

#define SLASH_1_IDX 7

#define YEAR_0_IDX 8
#define YEAR_1_IDX 9
#define YEAR_2_IDX 10
#define YEAR_3_IDX 11

#define PUNCTUATION_0_IDX 12

#define HOURS_0_IDX 13
#define HOURS_1_IDX 14

#define PUNCTUATION_1_IDX 15

#define MINUTES_0_IDX 16
#define MINUTES_1_IDX 17

#define PUNCTUATION_2_IDX 18

#define SECONDS_0_IDX 19
#define SECONDS_1_IDX 20

#define SPACE_IDX 21

#define TIMEZONE_SIGN_IDX 22
#define TIMEZONE_HOURS_0_IDX 23
#define TIMEZONE_HOURS_1_IDX 24
#define TIMEZONE_MINUTES_0_IDX 25
#define TIMEZONE_MINUTES_1_IDX 26

#define CLOSE_BRACKET_IDX 27

#define LOGS_FORMAT_SIZE 28